#!/usr/bin/env python3
"""Generate CPython 3.11 bytecode fixtures and stable disassembly goldens."""

from __future__ import annotations

import argparse
import dis
import io
import py_compile
import re
import sys
from pathlib import Path

from xdis import iscode

from decompyle3.controlflow import (
    analyze_control_flow,
    build_cfg,
    decode_exception_table,
)
from decompyle3.scanners.scanner311 import Scanner311


ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = ROOT / "test" / "simple_source" / "311"
BYTECODE_DIR = ROOT / "test" / "bytecode_3.11" / "generated"
GOLDEN_DIR = ROOT / "test" / "bytecode_3.11" / "golden"
TOKEN_GOLDEN_DIR = ROOT / "test" / "bytecode_3.11" / "golden_tokens"
CFG_GOLDEN_DIR = ROOT / "test" / "bytecode_3.11" / "golden_cfg"
ADDRESS_RE = re.compile(r"0x[0-9a-fA-F]+")


def stable_disassembly(source: Path) -> str:
    display_name = source.relative_to(ROOT).as_posix()
    code = compile(source.read_text(encoding="utf-8"), display_name, "exec")
    output = io.StringIO()
    dis.dis(code, file=output, depth=None, show_caches=True, adaptive=False)
    normalized = ADDRESS_RE.sub("0x...", output.getvalue())
    return (
        f"# Generated by CPython {sys.version_info.major}.{sys.version_info.minor}\n"
        f"# Source: {display_name}\n\n"
        f"{normalized}"
    )


def stable_value(value) -> str:
    if iscode(value):
        return f"<code {getattr(value, 'co_qualname', value.co_name)}>"
    if isinstance(value, tuple):
        body = ", ".join(stable_value(item) for item in value)
        if len(value) == 1:
            body += ","
        return f"({body})"
    if isinstance(value, list):
        return "[" + ", ".join(stable_value(item) for item in value) + "]"
    if isinstance(value, dict):
        items = sorted(value.items(), key=lambda item: repr(item[0]))
        return "{" + ", ".join(
            f"{stable_value(key)}: {stable_value(item)}"
            for key, item in items
        ) + "}"
    return repr(value)


def stable_call(call) -> str:
    return (
        "call("
        f"argc={call.argc},positional={call.positional_count},"
        f"keywords={stable_value(call.keyword_names)},"
        f"mode={call.receiver_mode},method={call.is_method},"
        f"null={call.has_null},self={call.has_self},"
        f"ex={call.uses_ex},starargs={call.has_starargs},"
        f"kwargs={call.has_kwargs})"
    )


def stable_function(function) -> str:
    return (
        "function("
        f"flags=0x{function.flags:x},code={function.code_name!r},"
        f"defaults={function.default_count},"
        f"kwdefaults={stable_value(function.kwdefault_names)},"
        f"annotations={stable_value(function.annotation_names)},"
        f"closure={stable_value(function.closure_names)})"
    )


def stable_tokens(source: Path) -> str:
    display_name = source.relative_to(ROOT).as_posix()
    root_code = compile(source.read_text(encoding="utf-8"), display_name, "exec")
    lines = [
        f"# Generated by CPython {sys.version_info.major}.{sys.version_info.minor}",
        f"# Source: {display_name}",
        "",
    ]
    for code in Scanner311.iter_code_objects(root_code):
        scanner = Scanner311()
        scanner.ingest(code)
        qualname = getattr(code, "co_qualname", code.co_name)
        lines.append(f"## code: {qualname}")
        for instruction in scanner.normalized_instructions:
            target = "-" if instruction.target is None else str(instruction.target)
            argument = "-" if instruction.arg is None else str(instruction.arg)
            jump_effect = (
                "-"
                if instruction.jump_stack_effect is None
                else str(instruction.jump_stack_effect)
            )
            details = [
                f"value={stable_value(instruction.argval)}",
                f"stack={instruction.stack_effect}/{jump_effect}",
                f"cache={stable_value(instruction.cache_offsets)}",
            ]
            if instruction.metadata:
                details.append(f"meta={stable_value(instruction.metadata)}")
            if instruction.call is not None:
                details.append(stable_call(instruction.call))
            if instruction.function is not None:
                details.append(stable_function(instruction.function))
            if instruction.is_internal:
                details.append("internal=True")
            lines.append(
                f"{instruction.physical_offset:04d} | "
                f"{instruction.logical_index:04d} | "
                f"{instruction.kind} | arg={argument} | target={target} | "
                + " | ".join(details)
            )
        lines.append("")
    return "\n".join(lines)


def stable_cfg(source: Path) -> str:
    display_name = source.relative_to(ROOT).as_posix()
    root_code = compile(source.read_text(encoding="utf-8"), display_name, "exec")
    lines = [
        f"# Generated by CPython {sys.version_info.major}.{sys.version_info.minor}",
        f"# Source: {display_name}",
        "",
    ]
    for code in Scanner311.iter_code_objects(root_code):
        scanner = Scanner311()
        scanner.ingest(code)
        graph = build_cfg(
            scanner.normalized_instructions,
            decode_exception_table(code),
        )
        analysis = analyze_control_flow(graph)
        qualname = getattr(code, "co_qualname", code.co_name)
        lines.append(f"## code: {qualname}")
        lines.append(graph.format())
        back_edges = ", ".join(
            f"B{source}->B{target}"
            for source, target in analysis.back_edges
        )
        loops = ", ".join(
            "B{}<-B{}:[{}]".format(
                loop.header,
                loop.latch,
                ",".join(f"B{block}" for block in sorted(loop.blocks)),
            )
            for loop in analysis.loops
        )
        lines.append(f"back_edges=[{back_edges}]")
        lines.append(f"natural_loops=[{loops}]")
        lines.append("")
    return "\n".join(lines)


def generate(check: bool) -> int:
    if sys.version_info[:2] != (3, 11):
        raise SystemExit(
            "CPython 3.11 is required; "
            f"running {sys.version_info.major}.{sys.version_info.minor}"
        )

    sources = sorted(SOURCE_DIR.glob("*.py"))
    if not sources:
        raise SystemExit(f"No corpus sources found in {SOURCE_DIR}")

    failures = []
    if not check:
        BYTECODE_DIR.mkdir(parents=True, exist_ok=True)
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        TOKEN_GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        CFG_GOLDEN_DIR.mkdir(parents=True, exist_ok=True)

    for source in sources:
        golden_path = GOLDEN_DIR / f"{source.stem}.dis"
        disassembly = stable_disassembly(source)
        token_path = TOKEN_GOLDEN_DIR / f"{source.stem}.tokens"
        token_stream = stable_tokens(source)
        cfg_path = CFG_GOLDEN_DIR / f"{source.stem}.cfg"
        cfg_stream = (
            stable_cfg(source)
            if source.stem
            in (
                "02_control_flow",
                "05_exceptions_with",
                "06_match",
                "07_exception_group",
            )
            else None
        )

        if check:
            artifacts = [
                (golden_path, disassembly),
                (token_path, token_stream),
            ]
            if cfg_stream is not None:
                artifacts.append((cfg_path, cfg_stream))
            for path, expected in artifacts:
                if not path.exists():
                    failures.append(f"missing {path.relative_to(ROOT)}")
                elif path.read_text(encoding="utf-8") != expected:
                    failures.append(f"stale {path.relative_to(ROOT)}")
            continue

        bytecode_path = BYTECODE_DIR / f"{source.stem}.pyc"
        display_name = source.relative_to(ROOT).as_posix()
        py_compile.compile(
            str(source),
            cfile=str(bytecode_path),
            dfile=display_name,
            doraise=True,
            invalidation_mode=py_compile.PycInvalidationMode.CHECKED_HASH,
        )
        golden_path.write_text(disassembly, encoding="utf-8")
        token_path.write_text(token_stream, encoding="utf-8")
        if cfg_stream is not None:
            cfg_path.write_text(cfg_stream, encoding="utf-8")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1

    action = "checked" if check else "generated"
    print(f"{action} {len(sources)} CPython 3.11 corpus files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify tracked disassembly goldens without rewriting files",
    )
    arguments = parser.parse_args()
    return generate(arguments.check)


if __name__ == "__main__":
    raise SystemExit(main())
