#!/usr/bin/env python3
"""Generate CPython 3.11 bytecode fixtures and stable disassembly goldens."""

from __future__ import annotations

import argparse
import dis
import io
import py_compile
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = ROOT / "test" / "simple_source" / "311"
BYTECODE_DIR = ROOT / "test" / "bytecode_3.11" / "generated"
GOLDEN_DIR = ROOT / "test" / "bytecode_3.11" / "golden"
ADDRESS_RE = re.compile(r"0x[0-9a-fA-F]+")


def stable_disassembly(source: Path) -> str:
    display_name = source.relative_to(ROOT).as_posix()
    code = compile(source.read_text(encoding="utf-8"), display_name, "exec")
    output = io.StringIO()
    dis.dis(code, file=output, depth=None, show_caches=True, adaptive=False)
    normalized = ADDRESS_RE.sub("0x...", output.getvalue())
    return (
        f"# Generated by CPython {sys.version_info.major}.{sys.version_info.minor}\n"
        f"# Source: {display_name}\n\n"
        f"{normalized}"
    )


def generate(check: bool) -> int:
    if sys.version_info[:2] != (3, 11):
        raise SystemExit(
            "CPython 3.11 is required; "
            f"running {sys.version_info.major}.{sys.version_info.minor}"
        )

    sources = sorted(SOURCE_DIR.glob("*.py"))
    if not sources:
        raise SystemExit(f"No corpus sources found in {SOURCE_DIR}")

    failures = []
    if not check:
        BYTECODE_DIR.mkdir(parents=True, exist_ok=True)
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)

    for source in sources:
        golden_path = GOLDEN_DIR / f"{source.stem}.dis"
        disassembly = stable_disassembly(source)

        if check:
            if not golden_path.exists():
                failures.append(f"missing {golden_path.relative_to(ROOT)}")
            elif golden_path.read_text(encoding="utf-8") != disassembly:
                failures.append(f"stale {golden_path.relative_to(ROOT)}")
            continue

        bytecode_path = BYTECODE_DIR / f"{source.stem}.pyc"
        display_name = source.relative_to(ROOT).as_posix()
        py_compile.compile(
            str(source),
            cfile=str(bytecode_path),
            dfile=display_name,
            doraise=True,
            invalidation_mode=py_compile.PycInvalidationMode.CHECKED_HASH,
        )
        golden_path.write_text(disassembly, encoding="utf-8")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1

    action = "checked" if check else "generated"
    print(f"{action} {len(sources)} CPython 3.11 corpus files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify tracked disassembly goldens without rewriting files",
    )
    arguments = parser.parse_args()
    return generate(arguments.check)


if __name__ == "__main__":
    raise SystemExit(main())
