#!/usr/bin/env python3
"""Generate CPython 3.11 bytecode fixtures and stable disassembly goldens."""

from __future__ import annotations

import argparse
import dis
import importlib.util
import io
import py_compile
import re
import sys
from importlib._bootstrap_external import _code_to_hash_pyc
from pathlib import Path

from xdis import iscode

from decompyle3.controlflow import (
    analyze_control_flow,
    build_cfg,
    decode_exception_table,
)
from decompyle3.errors import Decompyle3Error
from decompyle3.scanners.scanner311 import Scanner311


ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = ROOT / "test" / "simple_source" / "311"
OPCODE_FIXTURE_DIR = (
    ROOT / "test" / "bytecode_3.11" / "opcode_fixtures"
)
BYTECODE_DIR = ROOT / "test" / "bytecode_3.11" / "generated"
GOLDEN_DIR = ROOT / "test" / "bytecode_3.11" / "golden"
TOKEN_GOLDEN_DIR = ROOT / "test" / "bytecode_3.11" / "golden_tokens"
CFG_GOLDEN_DIR = ROOT / "test" / "bytecode_3.11" / "golden_cfg"
ADDRESS_RE = re.compile(r"0x[0-9a-fA-F]+")
COMPILE_MODE_RE = re.compile(r"# compile-mode: (exec|single|eval)")


def corpus_sources():
    """Return the main corpus followed by the focused opcode fixtures."""
    main_sources = sorted(SOURCE_DIR.glob("*.py"))
    opcode_fixtures = sorted(OPCODE_FIXTURE_DIR.rglob("*.py"))
    return [*main_sources, *opcode_fixtures]


def source_compile_mode(source: Path) -> str:
    """Read an optional first-line compile mode declaration."""
    first_line = source.read_text(encoding="utf-8").splitlines()[0]
    matched = COMPILE_MODE_RE.fullmatch(first_line)
    return matched.group(1) if matched else "exec"


def compile_source(source: Path):
    """Compile a fixture with CPython without constructing bytecode by hand."""
    display_name = source.relative_to(ROOT).as_posix()
    return compile(
        source.read_text(encoding="utf-8"),
        display_name,
        source_compile_mode(source),
        dont_inherit=True,
    )


def artifact_key(source: Path) -> Path:
    """Return a stable, extension-free output key for a corpus source."""
    if source.is_relative_to(SOURCE_DIR):
        return Path(source.stem)
    relative = source.relative_to(OPCODE_FIXTURE_DIR)
    return Path("opcode_fixtures") / relative.with_suffix("")


def artifact_paths(source: Path):
    """Return bytecode, dis, token, and CFG artifact paths for a source."""
    key = artifact_key(source)
    return (
        (BYTECODE_DIR / key).with_suffix(".pyc"),
        (GOLDEN_DIR / key).with_suffix(".dis"),
        (TOKEN_GOLDEN_DIR / key).with_suffix(".tokens"),
        (CFG_GOLDEN_DIR / key).with_suffix(".cfg"),
    )


def write_bytecode(source: Path, destination: Path) -> None:
    """Persist CPython-compiled code as a checked-hash pyc."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    display_name = source.relative_to(ROOT).as_posix()
    if source_compile_mode(source) == "exec":
        py_compile.compile(
            str(source),
            cfile=str(destination),
            dfile=display_name,
            doraise=True,
            invalidation_mode=py_compile.PycInvalidationMode.CHECKED_HASH,
        )
        return

    source_bytes = source.read_bytes()
    bytecode = _code_to_hash_pyc(
        compile_source(source),
        importlib.util.source_hash(source_bytes),
        checked=True,
    )
    destination.write_bytes(bytecode)


def stable_disassembly(source: Path) -> str:
    display_name = source.relative_to(ROOT).as_posix()
    code = compile_source(source)
    output = io.StringIO()
    dis.dis(code, file=output, depth=None, show_caches=True, adaptive=False)
    normalized = ADDRESS_RE.sub("0x...", output.getvalue())
    return (
        f"# Generated by CPython {sys.version_info.major}.{sys.version_info.minor}\n"
        f"# Source: {display_name}\n\n"
        f"{normalized}"
    )


def stable_value(value) -> str:
    if iscode(value):
        return f"<code {getattr(value, 'co_qualname', value.co_name)}>"
    if isinstance(value, tuple):
        body = ", ".join(stable_value(item) for item in value)
        if len(value) == 1:
            body += ","
        return f"({body})"
    if isinstance(value, list):
        return "[" + ", ".join(stable_value(item) for item in value) + "]"
    if isinstance(value, dict):
        items = sorted(value.items(), key=lambda item: repr(item[0]))
        return "{" + ", ".join(
            f"{stable_value(key)}: {stable_value(item)}"
            for key, item in items
        ) + "}"
    return repr(value)


def stable_call(call) -> str:
    return (
        "call("
        f"argc={call.argc},positional={call.positional_count},"
        f"keywords={stable_value(call.keyword_names)},"
        f"mode={call.receiver_mode},method={call.is_method},"
        f"null={call.has_null},self={call.has_self},"
        f"ex={call.uses_ex},starargs={call.has_starargs},"
        f"kwargs={call.has_kwargs})"
    )


def stable_function(function) -> str:
    return (
        "function("
        f"flags=0x{function.flags:x},code={function.code_name!r},"
        f"defaults={function.default_count},"
        f"kwdefaults={stable_value(function.kwdefault_names)},"
        f"annotations={stable_value(function.annotation_names)},"
        f"closure={stable_value(function.closure_names)})"
    )


def stable_tokens(source: Path) -> str:
    display_name = source.relative_to(ROOT).as_posix()
    root_code = compile_source(source)
    lines = [
        f"# Generated by CPython {sys.version_info.major}.{sys.version_info.minor}",
        f"# Source: {display_name}",
        "",
    ]
    for code in Scanner311.iter_code_objects(root_code):
        scanner = Scanner311()
        qualname = getattr(code, "co_qualname", code.co_name)
        lines.append(f"## code: {qualname}")
        try:
            scanner.ingest(code)
        except Decompyle3Error as error:
            lines.append(f"!! {type(error).__name__}: {error}")
            lines.append("")
            continue
        for instruction in scanner.normalized_instructions:
            target = "-" if instruction.target is None else str(instruction.target)
            argument = "-" if instruction.arg is None else str(instruction.arg)
            jump_effect = (
                "-"
                if instruction.jump_stack_effect is None
                else str(instruction.jump_stack_effect)
            )
            details = [
                f"value={stable_value(instruction.argval)}",
                f"stack={instruction.stack_effect}/{jump_effect}",
                f"cache={stable_value(instruction.cache_offsets)}",
            ]
            if instruction.metadata:
                details.append(f"meta={stable_value(instruction.metadata)}")
            if instruction.call is not None:
                details.append(stable_call(instruction.call))
            if instruction.function is not None:
                details.append(stable_function(instruction.function))
            if instruction.is_internal:
                details.append("internal=True")
            lines.append(
                f"{instruction.physical_offset:04d} | "
                f"{instruction.logical_index:04d} | "
                f"{instruction.kind} | arg={argument} | target={target} | "
                + " | ".join(details)
            )
        lines.append("")
    return "\n".join(lines)


def stable_cfg(source: Path) -> str:
    display_name = source.relative_to(ROOT).as_posix()
    root_code = compile_source(source)
    lines = [
        f"# Generated by CPython {sys.version_info.major}.{sys.version_info.minor}",
        f"# Source: {display_name}",
        "",
    ]
    for code in Scanner311.iter_code_objects(root_code):
        scanner = Scanner311()
        qualname = getattr(code, "co_qualname", code.co_name)
        lines.append(f"## code: {qualname}")
        try:
            scanner.ingest(code)
            graph = build_cfg(
                scanner.normalized_instructions,
                decode_exception_table(code),
            )
            analysis = analyze_control_flow(graph)
        except Decompyle3Error as error:
            lines.append(f"!! {type(error).__name__}: {error}")
            lines.append("")
            continue
        lines.append(graph.format())
        back_edges = ", ".join(
            f"B{source}->B{target}"
            for source, target in analysis.back_edges
        )
        loops = ", ".join(
            "B{}<-B{}:[{}]".format(
                loop.header,
                loop.latch,
                ",".join(f"B{block}" for block in sorted(loop.blocks)),
            )
            for loop in analysis.loops
        )
        lines.append(f"back_edges=[{back_edges}]")
        lines.append(f"natural_loops=[{loops}]")
        lines.append("")
    return "\n".join(lines)


def generate(check: bool) -> int:
    if sys.version_info[:2] != (3, 11):
        raise SystemExit(
            "CPython 3.11 is required; "
            f"running {sys.version_info.major}.{sys.version_info.minor}"
        )

    sources = corpus_sources()
    if not sources:
        raise SystemExit(
            f"No corpus sources found in {SOURCE_DIR} or {OPCODE_FIXTURE_DIR}"
        )

    failures = []
    if not check:
        BYTECODE_DIR.mkdir(parents=True, exist_ok=True)
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        TOKEN_GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        CFG_GOLDEN_DIR.mkdir(parents=True, exist_ok=True)

    for source in sources:
        (
            bytecode_path,
            golden_path,
            token_path,
            cfg_path,
        ) = artifact_paths(source)
        disassembly = stable_disassembly(source)
        token_stream = stable_tokens(source)
        cfg_stream = (
            stable_cfg(source)
            if source.is_relative_to(OPCODE_FIXTURE_DIR)
            or source.stem
            in {
                "02_control_flow",
                "05_exceptions_with",
                "06_match",
                "07_exception_group",
            }
            else None
        )

        if check:
            artifacts = [
                (golden_path, disassembly),
                (token_path, token_stream),
            ]
            if cfg_stream is not None:
                artifacts.append((cfg_path, cfg_stream))
            for path, expected in artifacts:
                if not path.exists():
                    failures.append(f"missing {path.relative_to(ROOT)}")
                elif path.read_text(encoding="utf-8") != expected:
                    failures.append(f"stale {path.relative_to(ROOT)}")
            continue

        for path in (golden_path, token_path, cfg_path):
            path.parent.mkdir(parents=True, exist_ok=True)
        write_bytecode(source, bytecode_path)
        golden_path.write_text(disassembly, encoding="utf-8")
        token_path.write_text(token_stream, encoding="utf-8")
        if cfg_stream is not None:
            cfg_path.write_text(cfg_stream, encoding="utf-8")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1

    action = "checked" if check else "generated"
    print(f"{action} {len(sources)} CPython 3.11 corpus files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify tracked disassembly goldens without rewriting files",
    )
    arguments = parser.parse_args()
    return generate(arguments.check)


if __name__ == "__main__":
    raise SystemExit(main())
